# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person'),
        ),
    ]
