# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
