# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20171226_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
