# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20171226_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
    ]
