# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_remove_person_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball_by_Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_Id', models.IntegerField(default=0)),
                ('Innings_Id', models.IntegerField(default=0)),
                ('Over_Id', models.IntegerField(default=0)),
                ('Ball_Id', models.IntegerField(default=0)),
                ('Team_Batting_Id', models.IntegerField()),
                ('Team_Bowling_Id', models.IntegerField()),
                ('Striker_Id', models.IntegerField()),
                ('Striker_Batting_Position', models.IntegerField()),
                ('Non_Striker_Id', models.IntegerField()),
                ('Bowler_Id', models.IntegerField()),
                ('Batsman_Scored', models.IntegerField()),
                ('Extra_Type', models.CharField(max_length=100)),
                ('Extra_Runs', models.IntegerField()),
                ('Player_dissimal_Id', models.IntegerField()),
                ('Dissimal_Type', models.CharField(max_length=100)),
                ('Fielder_Id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('Match_Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Match_Date', models.DateField(default=django.utils.timezone.now)),
                ('Team_Name_Id', models.IntegerField()),
                ('Opponent_Team_Id', models.IntegerField()),
                ('Season_Id', models.IntegerField()),
                ('Venue_Name', models.CharField(max_length=300)),
                ('Toss_Winner_Id', models.IntegerField()),
                ('Toss_Decision', models.CharField(max_length=100)),
                ('IS_Superover', models.IntegerField()),
                ('IS_Result', models.IntegerField()),
                ('Is_DuckWorthLewis', models.IntegerField()),
                ('Win_Type', models.CharField(max_length=100)),
                ('Won_By', models.IntegerField()),
                ('Match_Winner_Id', models.IntegerField()),
                ('Man_Of_The_Match_Id', models.IntegerField()),
                ('First_Umpire_Id', models.IntegerField()),
                ('Second_Umpire_Id', models.IntegerField()),
                ('City_Name', models.CharField(max_length=100)),
                ('Host_Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Player_Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Player_Name', models.CharField(max_length=100)),
                ('DOB', models.DateField(default=django.utils.timezone.now)),
                ('Batting_Hand', models.CharField(max_length=100)),
                ('Bowling_Skill', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Is_Umpire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_Id', models.IntegerField(default=0)),
                ('Player_Id', models.IntegerField(default=0)),
                ('Team_Id', models.IntegerField()),
                ('Is_Keeper', models.IntegerField()),
                ('Is_Captain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('Season_Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Season_Year', models.IntegerField()),
                ('Orange_Cap_Id', models.IntegerField()),
                ('Purple_Cap_Id', models.IntegerField()),
                ('Man_of_the_Series_Id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Team_Name', models.CharField(max_length=100)),
                ('Team_Short_Code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='office',
            name='person_id',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterUniqueTogether(
            name='player_match',
            unique_together=set([('Match_Id', 'Player_Id')]),
        ),
        migrations.AlterUniqueTogether(
            name='ball_by_ball',
            unique_together=set([('Match_Id', 'Innings_Id', 'Over_Id', 'Ball_Id')]),
        ),
    ]
