# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_auto_20171227_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Won_By',
            field=models.IntegerField(null=True),
        ),
    ]
