# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_auto_20171227_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Man_Of_The_Match_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='Match_Winner_Id',
            field=models.IntegerField(null=True),
        ),
    ]
