# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_auto_20171227_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball_by_ball',
            name='Batsman_Scored',
            field=models.IntegerField(null=True),
        ),
    ]
